# Detecting Exoplanets

#### 1. Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    ConfusionMatrixDisplay,
)

pd.set_option("display.max_columns", None)
sns.set_theme(style="whitegrid")

#### 2. Load Data

In [2]:
exoplanet_df = pd.read_csv('exoplanet_dataset.csv')

print("Dataset shape:", exoplanet_df.shape, "- 9564 rows with 49 features")

pd.set_option('display.max_columns', None)
display(exoplanet_df.head())

Dataset shape: (9564, 49) - 9564 rows with 49 features

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,koi_impact,koi_impact_err1,koi_impact_err2,koi_duration,koi_duration_err1,koi_duration_err2,koi_depth,koi_depth_err1,koi_depth_err2,koi_prad,koi_prad_err1,koi_prad_err2,koi_teq,koi_teq_err1,koi_teq_err2,koi_insol,koi_insol_err1,koi_insol_err2,koi_model_snr,koi_tce_plnt_num,koi_tce_delivname,koi_steff,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,2.95750,0.08190,-0.08190,615.8,19.5,-19.5,2.26,0.26,-0.15,793.0,NaN,NaN,93.59,29.45,-16.65,35.8,1.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,4.50700,0.11600,-0.11600,874.8,35.5,-35.5,2.83,0.32,-0.19,443.0,NaN,NaN,9.11,2.87,-1.62,25.8,2.0,q1_q17_dr25_tce,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,1.78220,0.03410,-0.03410,10829.0,171.0,-171.0,14.60,3.92,-1.31,638.0,NaN,NaN,39.30,31.04,-10.49,76.3,1.0,q1_q17_dr25_tce,5853.0,158.0,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,2.40641,0.00537,-0.00537,8079.2,12.8,-12.8,33.46,8.50,-2.83,1395.0,NaN,NaN,891.96,668.95,-230.35,505.6,1.0,q1_q17_dr25_tce,5805.0,157.0,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,1.65450,0.04200,-0.04200,603.3,16.9,-16.9,2.75,0.88,-0.35,1406.0,NaN,NaN,926.16,874.33,-314.24,40.9,1.0,q1_q17_dr25_tce,6031.0,169.0,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

#### Initial Overview

In [4]:
print("\nUpdated Data types and non-null values:")
print(exoplanet_df.info())

exoplanet_df.describe(include="all").T

Updated Data types and non-null values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 49 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   kepid              9564 non-null   int64
 1   kepoi_name         9564 non-null   object
 2   kepler_name        2673 non-null   object
 3   koi_disposition    9564 non-null   object
 4   koi_pdisposition   9564 non-null   object
 5   koi_score          8054 non-null   float64
 6   koi_fpflag_nt      9564 non-null   int64
 7   koi_fpflag_ss      9564 non-null   int64
 8   koi_fpflag_co      9564 non-null   int64
 9   koi_fpflag_ec      9564 non-null   int64
 10  koi_period         9564 non-null   float64
 11  koi_period_err1    9110 non-null   float64
 12  koi_period_err2    9110 non-null   float64
 13  koi_time0bk        9564 non-null   float64
 14  koi_time0bk_err1   9110 non-null   float64
 15  koi_time0bk_err2   9110 non-null   float64
 16  koi_impact         9201 non-null   float64
 17  koi_impact_err1    9110 non-null   float64
 18  koi_impact_err2    9110 non-null   float64
 19  koi_duration       9564 non-null   float64
 20  koi_duration_err1  9110 non-null   float64
 21  koi_duration_err2  9110 non-null   float64
 22  koi_depth          9201 non-null   float64
 23  koi_depth_err1     9110 non-null   float64
 24  koi_depth_err2     9110 non-null   float64
 25  koi_prad           9201 non-null   float64
 26  koi_prad_err1      9201 non-null   float64
 27  koi_prad_err2      9201 non-null   float64
 28  koi_teq            9201 non-null   float64
 29  koi_teq_err1       0 non-null      float64
 30  koi_teq_err2       0 non-null      float64
 31  koi_insol          9243 non-null   float64
 32  koi_insol_err1     9243 non-null   float64
 33  koi_insol_err2     9243 non-null   float64
 34  koi_model_snr      9201 non-null   float64
 35  koi_tce_plnt_num   9218 non-null   float64
 36  koi_tce_delivname  9218 non-null   object
 37  koi_steff          9201 non-null   float64
 38  koi_steff_err1     9096 non-null   float64
 39  koi_steff_err2     9081 non-null   float64
 40  koi_slogg          9201 non-null   float64
 41  koi_slogg_err1     9096 non-null   float64
 42  koi_slogg_err2     9096 non-null   float64
 43  koi_srad           9201 non-null   float64
 44  koi_srad_err1      9096 non-null   float64
 45  koi_srad_err2      9096 non-null   float64
 46  ra                 9564 non-null   float64
 47  dec                9564 non-null   float64
 48  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(5), object(5)
memory usage: 3.6+ MB
None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
kepid,9564.0,NaN,NaN,NaN,7690628.327373,2653459.080974,757450.0,5556034.25,7906892.0,9873066.5,12935144.0
kepoi_name,9564,9564,K00752.01,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kepler_name,2673,2673,Kepler-227 b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_disposition,9564,3,FALSE POSITIVE,4839,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_pdisposition,9564,2,FALSE POSITIVE,4847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_score,8054.0,NaN,NaN,NaN,0.480829,0.476928,0.0,0.0,0.334,0.998,1.0
koi_fpflag_nt,9564.0,NaN,NaN,NaN,0.208595,4.76729,0.0,0.0,0.0,0.0,465.0
koi_fpflag_ss,9564.0,NaN,NaN,NaN,0.232748,0.422605,0.0,0.0,0.0,0.0,1.0
koi_fpflag_co,9564.0,NaN,NaN,NaN,0.197512,0.398142,0.0,0.0,0.0,0.0,1.0
koi_fpflag_ec,9564.0,NaN,NaN,NaN,0.120033,0.325018,0.0,0.0,0.0,0.0,1.0
koi_period,9564.0,NaN,NaN,NaN,75.671358,1334.744046,0.241843,2.733684,9.752831,40.715178,129995.7784
koi_period_err1,9110.0,NaN,NaN,NaN,0.002148,0.008236,0.0,0.000005,0.000035,0.000276,0.1725
koi_period_err2,9110.0,NaN,NaN,NaN,-0.002148,0.008236,-0.1725,-0.000276,-0.000035,-0.000005,0.0
koi_time0bk,9564.0,NaN,NaN,NaN,166.183251,67.91896,120.515914,132.761718,137.224595,170.694603,1472.522306
koi_time0bk_err1,9110.0,NaN,NaN,NaN,0.009933,0.023097,0.000009,0.00124,0.00413,0.0105,0.569
koi_time0bk_err2,9110.0,NaN,NaN,NaN,-0.009933,0.023097,-0.569,-0.0105,-0.00413,-0.00124,-0.000009
koi_impact,9201.0,NaN,NaN,NaN,0.735105,3.348832,0.0,0.197,0.537,0.889,100.806
koi_impact_err1,9110.0,NaN,NaN,NaN,1.959861,9.421653,0.0,0.04,0.193,0.378,85.54
koi_impact_err2,9110.0,NaN,NaN,NaN,-0.332557,1.249828,-59.32,-0.445,-0.207,-0.046,0.0
koi_duration,9564.0,NaN,NaN,NaN,5.621606,6.471554,0.052,2.43775,3.7926,6.2765,138.54
koi_duration_err1,9110.0,NaN,NaN,NaN,0.339942,0.669823,0.0,0.0508,0.142,0.35,20.2
koi_duration_err2,9110.0,NaN,NaN,NaN,-0.339942,0.669823,-20.2,-0.35,-0.142,-0.0508,0.0
koi_depth,9201.0,NaN,NaN,NaN,23791.335898,82242.683149,0.0,159.9,421.1,1473.4,1541400.0
koi_depth_err1,9110.0,NaN,NaN,NaN,123.197563,4112.61523,0.0,9.6,20.75,49.5,388600.0
koi_depth_err2,9110.0,NaN,NaN,NaN,-123.197563,4112.61523,-388600.0,-49.5,-20.75,-9.6,0.0
koi_prad,9201.0,NaN,NaN,NaN,102.891778,3077.639126,0.08,1.4,2.39,14.93,200346.0
koi_prad_err1,9201.0,NaN,NaN,NaN,17.657684,391.138501,0.0,0.23,0.52,2.32,21640.0
koi_prad_err2,9201.0,NaN,NaN,NaN,-33.023314,1193.51991,-77180.0,-1.94,-0.3,-0.14,0.0
koi_teq,9201.0,NaN,NaN,NaN,1085.385828,856.351161,25.0,539.0,878.0,1379.0,14667.0
koi_teq_err1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_teq_err2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_insol,9243.0,NaN,NaN,NaN,7745.737023,159204.6652,0.0,20.15,141.6,870.29,10947554.55
koi_insol_err1,9243.0,NaN,NaN,NaN,3750.69791,55044.209142,0.0,9.19,72.83,519.415,3617132.59
koi_insol_err2,9243.0,NaN,NaN,NaN,-4043.522368,88388.311174,-5600031.33,-287.31,-40.26,-5.16,0.0
koi_model_snr,9201.0,NaN,NaN,NaN,259.895001,795.806615,0.0,12.0,23.0,78.0,9054.7
koi_tce_plnt_num,9218.0,NaN,NaN,NaN,1.243654,0.664573,1.0,1.0,1.0,1.0,8.0
koi_tce_delivname,9218,3,q1_q17_dr25_tce,8054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
koi_steff,9201.0,NaN,NaN,NaN,5706.82328,796.857947,2661.0,5310.0,5767.0,6112.0,15896.0
koi_steff_err1,9096.0,NaN,NaN,NaN,144.635554,47.052305,0.0,106.0,157.0,174.0,676.0
koi_steff_err2,9081.0,NaN,NaN,NaN,-162.265059,72.746348,-1762.0,-198.0,-160.0,-114.0,0.0
koi_slogg,9201.0,NaN,NaN,NaN,4.310157,0.432606,0.047,4.218,4.438,4.543,5.364
koi_slogg_err1,9096.0,NaN,NaN,NaN,0.120738,0.132837,0.0,0.042,0.07,0.149,1.472
koi_slogg_err2,9096.0,NaN,NaN,NaN,-0.143161,0.085477,-1.207,-0.196,-0.128,-0.088,0.0
koi_srad,9201.0,NaN,NaN,NaN,1.728712,6.127185,0.109,0.829,1.0,1.345,229.908
koi_srad_err1,9096.0,NaN,NaN,NaN,0.362292,0.93087,0.0,0.129,0.251,0.364,33.091
koi_srad_err2,9096.0,NaN,NaN,NaN,-0.394806,2.168213,-116.137,-0.25,-0.111,-0.069,0.0
ra,9564.0,NaN,NaN,NaN,292.060163,4.766657,279.85272,288.66077,292.261125,295.85916,301.72076
dec,9564.0,NaN,NaN,NaN,43.810433,3.601243,36.577381,40.777173,43.677504,46.714611,52.33601
koi_kepmag,9563.0,NaN,NaN,NaN,14.264606,1.385448,6.966,13.44,14.52,15.322,20.003

#### For an easier comprehension, we will rename the columns into their description.

In [5]:

exoplanet_df = exoplanet_df.rename(columns={'kepid':'KepID',
'kepoi_name':'KOIName',
'kepler_name':'KeplerName',
'koi_disposition':'ExoplanetArchiveDisposition',
'koi_pdisposition':'DispositionUsingKeplerData',
'koi_score':'DispositionScore',
'koi_fpflag_nt':'NotTransit-LikeFalsePositiveFlag',
'koi_fpflag_ss':'koi_fpflag_ss',
'koi_fpflag_co':'CentroidOffsetFalsePositiveFlag',
'koi_fpflag_ec':'EphemerisMatchIndicatesContaminationFalsePositiveFlag',
'koi_period':'OrbitalPeriod, days',
'koi_period_err1':'OrbitalPeriodUpperUnc, days',
'koi_period_err2':'OrbitalPeriodLowerUnc, days',
'koi_time0bk':'TransitEpoch, BKJD',
'koi_time0bk_err1':'TransitEpochUpperUnc, BKJD',
'koi_time0bk_err2':'TransitEpochLowerUnc, BKJD',
'koi_impact':'ImpactParamete',
'koi_impact_err1':'ImpactParameterUpperUnc',
'koi_impact_err2':'ImpactParameterLowerUnc',
'koi_duration':'TransitDuration, hrs',
'koi_duration_err1':'TransitDurationUpperUnc, hrs',
'koi_duration_err2':'TransitDurationLowerUnc, hrs',
'koi_depth':'TransitDepth, ppm',
'koi_insol':'InsolationFlux, Earthflux',
'koi_insol_err1':'InsolationFluxUpperUnc, Earthflux',
'koi_insol_err2':'InsolationFluxLowerUnc, Earthflux',
'koi_model_snr':'TransitSignal-to-Noise',
'koi_tce_plnt_num':'TCEPlanetNumber',
'koi_tce_delivname':'TCEDeliver',
'koi_steff':'StellarEffectiveTemperature, K',
'koi_steff_err1':'StellarEffectiveTemperatureUpperUnc, K',
'koi_steff_err2':'StellarEffectiveTemperatureLowerUnc, K',
'koi_depth_err1':'TransitDepthUpperUnc, ppm',
'koi_depth_err2':'TransitDepthLowerUnc, ppm',
'koi_prad':'PlanetaryRadius, Earthradii',
'koi_prad_err1':'PlanetaryRadiusUpperUnc, Earthradii',
'koi_prad_err2':'PlanetaryRadiusLowerUnc, Earthradii',
'koi_teq':'EquilibriumTemperature, K',
'koi_teq_err1':'EquilibriumTemperatureUpperUnc, K',
'koi_teq_err2':'EquilibriumTemperatureLowerUnc, K',
'koi_slogg':'StellarSurfaceGravity, log10(cm/s^2)',
'koi_slogg_err1':'StellarSurfaceGravityUpperUnc, log10(cm/s^2)',
'koi_slogg_err2':'StellarSurfaceGravityLowerUnc, log10(cm/s^2)',
'koi_srad':'StellarRadius, Solarradii',
'koi_srad_err1':'StellarRadiusUpperUnc, Solarradii',
'koi_srad_err2':'StellarRadiusLowerUnc, Solarradii',
'ra':'RA, decimaldegrees',
'dec':'Dec, decimaldegrees',
'koi_kepmag':'Kepler-band, mag'
})

#### Analysis (Duplicate/Missing)

In [7]:
missing_values_percentage = (exoplanet_df.isnull().mean() * 100).sort_values(ascending=False).round(2)
print("\nPercentage of missing values in each column:")
print(missing_values_percentage)

Percentage of missing values in each column:
EquilibriumTemperatureLowerUnc, K                        100.00
EquilibriumTemperatureUpperUnc, K                        100.00
KeplerName                                                72.05
DispositionScore                                          15.79
StellarEffectiveTemperatureLowerUnc, K                     5.05
StellarRadiusLowerUnc, Solarradii                          4.89
StellarRadiusUpperUnc, Solarradii                          4.89
StellarSurfaceGravityLowerUnc, log10(cm/s^2)               4.89
StellarSurfaceGravityUpperUnc, log10(cm/s^2)               4.89
StellarEffectiveTemperatureUpperUnc, K                     4.89
TransitDepthLowerUnc, ppm                                  4.75
ImpactParameterLowerUnc                                    4.75
TransitDepthUpperUnc, ppm                                  4.75
TransitDurationLowerUnc, hrs                               4.75
TransitDurationUpperUnc, hrs                               4.75
ImpactParameterUpperUnc                                    4.75
TransitEpochLowerUnc, BKJD                                 4.75
TransitEpochUpperUnc, BKJD                                 4.75
OrbitalPeriodLowerUnc, days                                4.75
OrbitalPeriodUpperUnc, days                                4.75
ImpactParamete                                             3.80
PlanetaryRadiusUpperUnc, Earthradii                        3.80
StellarRadius, Solarradii                                  3.80
StellarSurfaceGravity, log10(cm/s^2)                       3.80
EquilibriumTemperature, K                                  3.80
PlanetaryRadiusLowerUnc, Earthradii                        3.80
PlanetaryRadius, Earthradii                                3.80
TransitDepth, ppm                                          3.80
StellarEffectiveTemperature, K                             3.80
TransitSignal-to-Noise                                     3.80
TCEPlanetNumber                                            3.62
TCEDeliver                                                 3.62
InsolationFlux, Earthflux                                  3.36
InsolationFluxUpperUnc, Earthflux                          3.36
InsolationFluxLowerUnc, Earthflux                          3.36
Kepler-band, mag                                           0.01
KOIName                                                    0.00
TransitDuration, hrs                                       0.00
TransitEpoch, BKJD                                         0.00
OrbitalPeriod, days                                        0.00
EphemerisMatchIndicatesContaminationFalsePositiveFlag      0.00
CentroidOffsetFalsePositiveFlag                            0.00
koi_fpflag_ss                                              0.00
NotTransit-LikeFalsePositiveFlag                           0.00
DispositionUsingKeplerData                                 0.00
ExoplanetArchiveDisposition                                0.00
RA, decimaldegrees                                         0.00
Dec, decimaldegrees                                        0.00
KepID                                                      0.00
dtype: float64

In [18]:
# Columns with 100% missing values are given:
full_missing_cols = ['EquilibriumTemperatureUpperUnc, K', 'EquilibriumTemperatureLowerUnc, K']

# irrelevat columns
irrelevant_columns = ['KepID', "KOIName", "KeplerName", "TCEDeliver"]

# Columns to drop
columns_to_drop = exoplanet_df.drop(columns=full_missing_cols + irrelevant_columns)

print(columns_to_drop.columns.shape)
columns_to_drop.head()

(43,)

,ExoplanetArchiveDisposition,DispositionUsingKeplerData,DispositionScore,NotTransit-LikeFalsePositiveFlag,koi_fpflag_ss,CentroidOffsetFalsePositiveFlag,EphemerisMatchIndicatesContaminationFalsePositiveFlag,"OrbitalPeriod, days","OrbitalPeriodUpperUnc, days","OrbitalPeriodLowerUnc, days","TransitEpoch, BKJD","TransitEpochUpperUnc, BKJD","TransitEpochLowerUnc, BKJD",ImpactParamete,ImpactParameterUpperUnc,ImpactParameterLowerUnc,"TransitDuration, hrs","TransitDurationUpperUnc, hrs","TransitDurationLowerUnc, hrs","TransitDepth, ppm","TransitDepthUpperUnc, ppm","TransitDepthLowerUnc, ppm","PlanetaryRadius, Earthradii","PlanetaryRadiusUpperUnc, Earthradii","PlanetaryRadiusLowerUnc, Earthradii","EquilibriumTemperature, K","InsolationFlux, Earthflux","InsolationFluxUpperUnc, Earthflux","InsolationFluxLowerUnc, Earthflux",TransitSignal-to-Noise,TCEPlanetNumber,"StellarEffectiveTemperature, K","StellarEffectiveTemperatureUpperUnc, K","StellarEffectiveTemperatureLowerUnc, K","StellarSurfaceGravity, log10(cm/s^2)","StellarSurfaceGravityUpperUnc, log10(cm/s^2)","StellarSurfaceGravityLowerUnc, log10(cm/s^2)","StellarRadius, Solarradii","StellarRadiusUpperUnc, Solarradii","StellarRadiusLowerUnc, Solarradii","RA, decimaldegrees","Dec, decimaldegrees","Kepler-band, mag"
0,CONFIRMED,CANDIDATE,1.000,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,-0.002160,0.146,0.318,-0.146,2.95750,0.08190,-0.08190,615.8,19.5,-19.5,2.26,0.26,-0.15,793.0,93.59,29.45,-16.65,35.8,1.0,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,CONFIRMED,CANDIDATE,0.969,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,-0.003520,0.586,0.059,-0.443,4.50700,0.11600,-0.11600,874.8,35.5,-35.5,2.83,0.32,-0.19,443.0,9.11,2.87,-1.62,25.8,2.0,5455.0,81.0,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,CANDIDATE,CANDIDATE,0.000,0,0,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,-0.000581,0.969,5.126,-0.077,1.78220,0.03410,-0.03410,10829.0,171.0,-171.0,14.60,3.92,-1.31,638.0,39.30,31.04,-10.49,76.3,1.0,5853.0,158.0,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,-0.000115,1.276,0.115,-0.092,2.40641,0.00537,-0.00537,8079.2,12.8,-12.8,33.46,8.50,-2.83,1395.0,891.96,668.95,-230.35,505.6,1.0,5805.0,157.0,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,CONFIRMED,CANDIDATE,1.000,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,-0.001130,0.701,0.235,-0.478,1.65450,0.04200,-0.04200,603.3,16.9,-16.9,2.75,0.88,-0.35,1406.0,926.16,874.33,-314.24,40.9,1.0,6031.0,169.0,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509